version: '3.3'

services:
  django_web:
    environment:
      PRODUCTION: "true"
    secrets:
      - djangodb.cnf
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  mysqldb:
    secrets:
      - mysql_db
      - mysql_root_pass
      - mysql_user
      - mysql_pass
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

secrets:
  djangodb.cnf:
    file: ./conf/djangodb.cnf
  mysql_root_pass:
    file: ./conf/mysqldb/mysql_root_pass
  mysql_db:
    file: ./conf/mysqldb/mysql_db
  mysql_user:
    file: ./conf/mysqldb/mysql_user
  mysql_pass:
    file: ./conf/mysqldb/mysql_pass
