version: '3.3'

services:
  django_web:
    labels:
      com.example.service: "django_web"
      com.example.description: "Use for the main web process that serve django application."
    image: narendra3425/apache_wsgi:2.4
    volumes:
      - ./src/:/app:ro
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_pass
      MYSQL_DATABASE_FILE:  /run/secrets/mysql_db
      MYSQL_USER_FILE: /run/secrets/mysql_user
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_pass
    volumes:
      - django_data:/var/lib/mysql:rw

  proxy:
    labels:
      com.example.service: "proxy"
      com.example.description: "Act as reverse proxy for apache server"
    image: narendra3425/nginx:1.14-alpine
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - django_web
    
volumes:
  django_data:
