version: '3.3'

services:
  django_web:
    container_name: django_web
    build:  
      context: .
      dockerfile: httpd_wsgi.Dockerfile
      args:
        DJANGO_PROJECT_NAME: DjangoApp
    environment:
      PRODUCTION: "true"
    volumes:
      - ./conf/djangodb.cnf:/run/secrets/djangodb.cnf:ro

  mysqldb:
    container_name: mysqldb
    restart: always
    volumes:
      - ./conf/mysqldb:/run/secrets:ro

  proxy:
    container_name: nginx_proxy
    build:
      context: .
      dockerfile: nginx.Dockerfile
    volumes:
      - ./conf/nginx.conf:/etc/nginx/conf.d/default.conf
    